import type{Puzzle}from'../types/game';export const puzzles:Puzzle[]=[
{id:'calendar-code',title:'Desk Calendar Code',type:'numeric',answer:'1847',description:'Connect the marked calendar date with the stopped clock year plaque.',clue:'Calendar Oct 18 and year plaque 47 produce 1847.',grantsNotes:['Calendar + stopped clock = 1847'],hints:['Study the calendar close-up.','Use the marked day before the small year plaque.','The four digits are 18 then 47.']},
{id:'desk-keypad',title:'Desk Drawer Keypad',type:'numeric',answer:'1847',description:'Enter the four-digit code to release the locked drawer.',clue:'The desk calendar puzzle records 1847.',requires:['calendar-code'],grantsItems:['red-lens','torn-note','photograph','metal-gear','projector-slide','small-mirror','mechanical-handle'],videoId:'desk',updatesRoom:'desk',hints:['The keypad needs four digits.','Your notebook has the calendar code.','Enter 1847.']},
{id:'photo-lens',title:'Hidden Photograph Message',type:'lens',answer:'△○✦♜',description:'Move the red lens over the photograph to reveal symbols.',clue:'The transparent red lens exposes hidden ink.',requires:['desk-keypad'],grantsNotes:['Red-lens photograph order: △ ○ ✦ ♜'],hints:['Try an item on the photograph.','The red lens filters the hidden ink.','Read the symbols left-to-right: △ ○ ✦ ♜.']},
{id:'bookshelf-order',title:'Bookshelf Order',type:'bookOrder',answer:['△','○','✦','♜'],description:'Arrange the marked books to match the photograph symbols.',clue:'Book spines carry the same marks.',requires:['photo-lens'],videoId:'bookshelf',updatesRoom:'bookshelf',hints:['Some spines repeat the photograph marks.','Match the red-lens photograph order.','Arrange △, ○, ✦, ♜.']},
{id:'projector-assembly',title:'Projector Assembly',type:'assembly',answer:['metal-gear','projector-slide'],description:'Install the missing gear and slide into the projector compartment.',clue:'The open shelf reveals two empty fittings.',requires:['bookshelf-order'],videoId:'projector',grantsNotes:['Projected star path: ☉ ☽ ♃ ♄ ✦'],hints:['The projector needs two inventory parts.','Use the gear and glass slide.','Install Metal Gear and Projector Slide.']},
{id:'star-chart',title:'Star Chart Sequence',type:'symbol',answer:['☉','☽','♃','♄','✦'],description:'Compare the projected path with the framed star chart.',clue:'The star chart labels the projected route.',requires:['projector-assembly'],grantsNotes:['Cabinet symbol sequence: ☉ ☽ ♃ ♄ ✦'],hints:['Compare projection and chart.','Follow the illuminated route.','Use ☉ ☽ ♃ ♄ ✦.']},
{id:'cabinet-lock',title:'Mechanical Cabinet Symbol Lock',type:'symbol',answer:['☉','☽','♃','♄','✦'],description:'Enter the five celestial symbols.',clue:'The star chart sequence opens the cabinet.',requires:['star-chart'],grantsItems:['cipher-disk','pocket-watch'],videoId:'machine',updatesRoom:'cabinet',hints:['It is a five-symbol lock.','Use the star chart note.','Enter ☉ ☽ ♃ ♄ ✦.']},
{id:'cipher-note',title:'Cipher Disk',type:'cipher',answer:'TIME REFLECTS WHAT MEMORY HIDES',description:'Set the cipher disk to the pocket watch number 7 and decode the torn note.',clue:'Pocket watch engraving: offset 7.',requires:['cabinet-lock'],grantsNotes:['Decoded note: TIME REFLECTS WHAT MEMORY HIDES'],hints:['The watch gives the cipher setting.','Rotate the disk to 7.','The decoded phrase is TIME REFLECTS WHAT MEMORY HIDES.']},
{id:'mirror-clock',title:'Mirror and Clock',type:'mirror',answer:'10:35',description:'Drag the small mirror over reversed marks behind the clock.',clue:'Reflection reveals the true time.',requires:['cipher-note'],grantsNotes:['Clock hands must read 10:35'],hints:['The decoded phrase mentions reflects.','Use the small mirror behind the clock.','The reflected time is 10:35.']},
{id:'clock-mechanism',title:'Clock Mechanism',type:'clock',answer:'10:35',description:'Set the hour and minute hands to the reflected time.',clue:'The mirror revealed 10:35.',requires:['mirror-clock'],videoId:'machine',updatesRoom:'study',hints:['Use the reflected clock note.','Set hour near ten and minute on seven.','Set 10:35.']},
{id:'machine-sequence',title:'Machine Sequence',type:'machine',answer:['amber','blue','amber','white','blue'],description:'Repeat the light-and-sound sequence; visual lamps mirror the audio.',clue:'Previous clue colors: desk amber, moon blue, brass amber, projector white, cabinet blue.',requires:['clock-mechanism'],grantsNotes:['Final door code displayed by machine: 7391'],hints:['Review room light colors.','The sequence is visible on machine lamps.','Press amber, blue, amber, white, blue.']},
{id:'final-door',title:'Final Door Code',type:'numeric',answer:'7391',description:'Enter the code displayed by the awakened machine.',clue:'The machine display reads 7391.',requires:['machine-sequence'],videoId:'door',updatesRoom:'door',hints:['The powered machine displays digits.','Read the brass counter on the machine.','Enter 7391.']}
];
