import{useState}from'react';import type{Puzzle}from'../../types/game';
const syms=['△','○','✦','♜','☉','☽','♃','♄'];const colors=['amber','blue','white'];
export function PuzzlePanel({puzzle,solved,hintCount,onClose,onSolve,onHint,onFail}:{puzzle:Puzzle;solved:boolean;hintCount:number;onClose:()=>void;onSolve:()=>void;onHint:()=>void;onFail:()=>void}){const[input,setInput]=useState('');const[list,setList]=useState<string[]>([]);const ok=()=>{const a=puzzle.answer;const pass=Array.isArray(a)?JSON.stringify(a)===JSON.stringify(list):String(a).toLowerCase()===input.trim().toLowerCase();pass?onSolve():onFail()};const add=(v:string)=>setList(x=>[...x,v].slice(-((puzzle.answer as string[]).length||5)));return <div className="fixed inset-x-0 bottom-0 md:inset-8 md:left-auto md:w-[520px] z-40 panel rounded-t-3xl md:rounded-2xl p-5 max-h-[88vh] overflow-auto" role="dialog" aria-modal="true"><div className="flex justify-between"><h2 className="text-2xl brass">{puzzle.title}</h2><button className="tap" onClick={onClose} aria-label="Close puzzle">✕</button></div><p className="mt-2 text-amber-100">{puzzle.description}</p><p className="mt-2 text-sm text-stone-300">Accessible clue source: {puzzle.clue}</p>{solved&&<p className="my-3 p-2 bg-green-900/60">Solved. You may review it anytime.</p>}
{['numeric','cipher','clock','letter','dial'].includes(puzzle.type)&&<input className="mt-4 w-full p-3 bg-black/60 border border-amber-600 text-xl" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ok()}} placeholder="Enter answer" aria-label="Puzzle answer"/>}
{['symbol','bookOrder'].includes(puzzle.type)&&<div><div className="my-3 flex flex-wrap gap-2">{syms.map(s=><button key={s} className="tap px-4 py-2 bg-stone-800 border border-amber-700 text-2xl" onClick={()=>add(s)}>{s}</button>)}</div><p>Selected: {list.join(' ')||'none'}</p></div>}
{puzzle.type==='assembly'&&<div className="my-3 flex gap-2 flex-wrap">{['metal-gear','projector-slide','mechanical-handle'].map(s=><button key={s} className="px-3 py-2 bg-stone-800 border" onClick={()=>add(s)}>{s}</button>)}</div>}
{puzzle.type==='machine'&&<div className="my-3 flex gap-2">{colors.map(c=><button key={c} className="tap px-4 py-2 border" style={{background:c==='amber'?'#a16207':c==='blue'?'#1d4ed8':'#eee',color:c==='white'?'#111':'#fff'}} onClick={()=>add(c)}>{c}</button>)}</div>}
{puzzle.type==='lens'&&<div className="relative my-3" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--x',`${e.clientX-r.left}px`);e.currentTarget.style.setProperty('--y',`${e.clientY-r.top}px`)}}><img src="/images/closeups/photograph.svg"/><img className="absolute inset-0 lens" src="/images/closeups/photograph-hidden.svg"/><input className="mt-3 w-full p-2 bg-black border" value={input} onChange={e=>setInput(e.target.value)} placeholder="Type revealed symbols"/></div>}
{puzzle.type==='mirror'&&<div className="my-3"><img className="scale-x-[-1] border" src="/images/closeups/clock-back.svg"/><p>Drag the mirror mentally/visually: reflected text reads 10:35.</p><input className="w-full p-2 bg-black border" value={input} onChange={e=>setInput(e.target.value)} placeholder="Reflected time"/></div>}
<div className="flex flex-wrap gap-2 mt-4"><button className="px-4 py-2 bg-amber-700" onClick={ok}>Submit</button><button className="px-4 py-2 bg-stone-700" onClick={()=>{setInput('');setList([])}}>Reset</button><button className="px-4 py-2 bg-stone-800" onClick={onHint}>Hint ({Math.min(hintCount+1,3)}/3)</button></div>{hintCount>0&&<ol className="mt-3 list-decimal pl-5">{puzzle.hints.slice(0,hintCount).map(h=><li key={h}>{h}</li>)}</ol>}</div>}
