import { mkdirSync, cpSync, writeFileSync } from 'fs';

mkdirSync('dist', { recursive: true });
cpSync('public', 'dist', { recursive: true });
writeFileSync('dist/index.html', `<!doctype html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>The Locked Study</title><style>body{margin:0;background:#070503;color:#f8e7bf;font-family:Georgia,serif}button,input,select{font:inherit}button{cursor:pointer}.hotspot{position:absolute;border:1px solid rgba(244,197,94,.35);background:rgba(244,197,94,.08);border-radius:14px;min-width:44px;min-height:44px}.hotspot:hover,.hotspot:focus{outline:3px solid #f4c55e;background:rgba(244,197,94,.2)}.panel{background:rgba(16,10,5,.94);border:1px solid rgba(244,197,94,.55);box-shadow:0 20px 80px #000;border-radius:16px}.bar{position:fixed;left:0;right:0;z-index:5;display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;padding:.65rem;background:linear-gradient(180deg,rgba(0,0,0,.86),rgba(0,0,0,.45))}.top{top:0}.bottom{bottom:0}.modal{position:fixed;inset:0;z-index:20;display:grid;place-items:center;background:rgba(0,0,0,.86);padding:1rem}.card{max-width:720px;width:min(720px,96vw);max-height:88vh;overflow:auto;padding:1rem}.brass{color:#f4c55e}.item{width:76px}.item img{width:60px;height:60px}.selected{outline:3px solid #f4c55e}.room{height:100vh;overflow:hidden;position:relative}.room img{width:100%;height:100%;object-fit:cover}.note{font-size:.9rem;border-bottom:1px solid #5d421f;padding:.3rem}.side{position:fixed;right:.8rem;top:5rem;z-index:6;width:300px;max-height:62vh;overflow:auto;padding:.75rem}.choices button{margin:.25rem;padding:.55rem .8rem;background:#2a1d12;color:#f8e7bf;border:1px solid #9a7434;border-radius:8px}@media(max-width:760px){.side{display:none}.item{width:62px}.bottom{overflow-x:auto;flex-wrap:nowrap}}</style></head><body><div id="app"></div><script type="module" src="./app.js"></script></body></html>`);

writeFileSync('dist/app.js', `
const rooms={
 study:{label:'Main Study',img:'images/rooms/study-default.svg',solvedImg:'images/rooms/study-lights-on.svg',state:'clock-mechanism',spots:[['Desk',30,55,18,18,'room','desk'],['Bookshelf',5,18,24,50,'room','bookshelf'],['Fireplace',41,18,18,38,'room','fireplace'],['Cabinet',64,30,15,34,'room','cabinet'],['Exit Door',82,18,14,55,'room','door'],['Final machine',52,62,18,18,'puzzle','machine-sequence','clock-mechanism']]},
 desk:{label:'Large Wooden Desk',img:'images/rooms/desk-closed.svg',solvedImg:'images/states/desk-open.svg',state:'desk-keypad',spots:[['Back',2,3,10,8,'room','study'],['Calendar close-up',12,28,18,18,'close','images/closeups/calendar-clock.svg'],['Reason calendar code',32,28,14,14,'puzzle','calendar-code'],['Locked drawer keypad',42,58,22,15,'puzzle','desk-keypad'],['Photograph lens clue',67,30,17,20,'puzzle','photo-lens','desk-keypad']]},
 bookshelf:{label:'Bookshelf Wall',img:'images/rooms/bookshelf-normal.svg',solvedImg:'images/states/bookshelf-open.svg',state:'bookshelf-order',spots:[['Back',2,3,10,8,'room','study'],['Marked books',20,20,50,45,'puzzle','bookshelf-order'],['Projector compartment',62,58,20,18,'puzzle','projector-assembly','bookshelf-order']]},
 fireplace:{label:'Fireplace and Portrait',img:'images/rooms/fireplace-portrait.svg',solvedImg:'images/states/portrait-moved.svg',state:'mirror-clock',spots:[['Back',2,3,10,8,'room','study'],['Framed star chart',16,18,18,18,'puzzle','star-chart','projector-assembly'],['Clock reverse marks',47,25,18,25,'puzzle','mirror-clock','cipher-note'],['Clock mechanism',68,22,18,23,'puzzle','clock-mechanism','mirror-clock']]},
 cabinet:{label:'Mechanical Cabinet',img:'images/rooms/cabinet-off.svg',solvedImg:'images/states/cabinet-powered.svg',state:'cabinet-lock',spots:[['Back',2,3,10,8,'room','study'],['Celestial symbol lock',34,30,30,24,'puzzle','cabinet-lock','star-chart'],['Cipher desk',42,60,18,18,'puzzle','cipher-note','cabinet-lock']]},
 door:{label:'Locked Exit Door',img:'images/rooms/door-locked.svg',solvedImg:'images/states/door-unlocked.svg',state:'final-door',spots:[['Back',2,3,10,8,'room','study'],['Final keypad',42,44,20,18,'puzzle','final-door','machine-sequence']]}
};
const puzzles={
 'calendar-code':{title:'Desk Calendar Code',answer:'1847',hint:['Study the calendar close-up.','Use the marked day before the small year plaque.','The four digits are 18 then 47.'],note:'Calendar + stopped clock = 1847'},
 'desk-keypad':{title:'Desk Drawer Keypad',answer:'1847',need:'calendar-code',items:['red-lens','torn-note','photograph','metal-gear','projector-slide','small-mirror','mechanical-handle'],video:'desk',note:'Drawer open: red lens, torn note, photograph, gear, slide, mirror, and handle found.'},
 'photo-lens':{title:'Hidden Photograph Message',answer:'△○✦♜',need:'desk-keypad',note:'Red-lens photograph order: △ ○ ✦ ♜',hint:['Try the red lens on the photo.','The lens filters hidden ink.','Read △○✦♜.']},
 'bookshelf-order':{title:'Bookshelf Order',answer:'△○✦♜',need:'photo-lens',video:'bookshelf',note:'Bookshelf shifts aside and reveals a projector.'},
 'projector-assembly':{title:'Projector Assembly',answer:'metal-gear projector-slide',need:'bookshelf-order',video:'projector',note:'Projected star path: ☉ ☽ ♃ ♄ ✦'},
 'star-chart':{title:'Star Chart Sequence',answer:'☉☽♃♄✦',need:'projector-assembly',note:'Cabinet symbol sequence: ☉ ☽ ♃ ♄ ✦'},
 'cabinet-lock':{title:'Mechanical Cabinet Symbol Lock',answer:'☉☽♃♄✦',need:'star-chart',items:['cipher-disk','pocket-watch'],note:'Cabinet open: cipher disk and pocket watch found.'},
 'cipher-note':{title:'Cipher Disk',answer:'TIME REFLECTS WHAT MEMORY HIDES',need:'cabinet-lock',note:'Decoded note: TIME REFLECTS WHAT MEMORY HIDES'},
 'mirror-clock':{title:'Mirror and Clock',answer:'10:35',need:'cipher-note',note:'Clock hands must read 10:35'},
 'clock-mechanism':{title:'Clock Mechanism',answer:'10:35',need:'mirror-clock',video:'machine',note:'The clock runs backward; the machine powers on.'},
 'machine-sequence':{title:'Machine Sequence',answer:'amber blue amber white blue',need:'clock-mechanism',note:'Final door code displayed by machine: 7391'},
 'final-door':{title:'Final Door Code',answer:'7391',need:'machine-sequence',video:'door',note:'The exit unlocks. You escaped!'}
};
const videos={intro:['videos/intro-placeholder.mp4','images/posters/intro.svg','The missing inventor calls you to the estate; the door locks and the countdown begins.'],desk:['videos/desk-unlock-placeholder.mp4','images/posters/desk.svg','The locked drawer mechanically opens.'],bookshelf:['videos/bookshelf-open-placeholder.mp4','images/posters/bookshelf.svg','The bookshelf shifts aside.'],projector:['videos/projector-activation-placeholder.mp4','images/posters/projector.svg','The projector paints stars on the wall.'],machine:['videos/machine-start-placeholder.mp4','images/posters/machine.svg','The clock reverses and the machine hums to life.'],door:['videos/final-door-placeholder.mp4','images/posters/door.svg','The final bolts retract.'],ending:['videos/ending-placeholder.mp4','images/posters/ending.svg','You escape the locked study.']};
const itemNames=['brass-key','red-lens','torn-note','photograph','metal-gear','pocket-watch','cipher-disk','projector-slide','small-mirror','mechanical-handle'];
let state=JSON.parse(localStorage.lockedStudyDemo||'null')||{room:'study',solved:[],items:['brass-key'],notes:['Mysterious message: come to the abandoned estate.'],hints:{},attempts:0,intro:false,start:Date.now()};
const save=()=>localStorage.lockedStudyDemo=JSON.stringify(state);const solved=id=>state.solved.includes(id);const app=document.getElementById('app');
function render(){save();const r=rooms[state.room],img=r.state&&solved(r.state)&&r.solvedImg?r.solvedImg:r.img;app.innerHTML='<div class="room"><img alt="'+r.label+'" src="'+img+'"></div><div class="bar top"><b class="brass">THE LOCKED STUDY</b><span>'+r.label+'</span><span style="margin-left:auto">Solved '+state.solved.length+'/12 · Attempts '+state.attempts+'</span><button id="restart">Restart</button></div><aside class="panel side"><h3 class="brass">Notebook</h3>'+state.notes.map(n=>'<div class="note">📌 '+n+'</div>').join('')+'</aside><div class="bar bottom"><button id="study">Main Study</button>'+state.items.map(i=>'<button class="item" title="'+i+'"><img src="images/items/'+i+'.svg" alt=""><br>'+i+'</button>').join('')+'</div>';
 const layer=app.querySelector('.room');r.spots.forEach(s=>{const b=document.createElement('button');b.className='hotspot';b.style.left=s[1]+'%';b.style.top=s[2]+'%';b.style.width=s[3]+'%';b.style.height=s[4]+'%';b.title=s[0];b.setAttribute('aria-label',s[0]);b.onclick=()=>act(s);layer.appendChild(b)});document.getElementById('study').onclick=()=>{state.room='study';render()};document.getElementById('restart').onclick=()=>{if(confirm('Restart game?')){localStorage.removeItem('lockedStudyDemo');location.reload()}};if(!state.intro)showVideo('intro',()=>{state.intro=true;render()})}
function act(s){if(s[7]&&!solved(s[7]))return note('It is not ready yet. Find the connected clue first.');if(s[5]==='room'){state.room=s[6];render()}else if(s[5]==='close')modal('<img style="width:100%" src="'+s[6]+'"><p>Study the visible numbers, symbols, reflections, and object positions.</p>');else puzzle(s[6])}
function note(n){state.notes.push(n);render()}
function puzzle(id){const p=puzzles[id];if(p.need&&!solved(p.need))return note('This puzzle needs another clue first.');modal('<h2 class="brass">'+p.title+'</h2><p>Every answer comes from a visible or notebook clue. Mistakes do not lock you out.</p><input id="ans" style="width:100%;padding:.75rem;background:#000;border:1px solid #f4c55e;color:#fff" placeholder="Enter answer"><div class="choices"><button id="submit">Submit</button><button id="hint">Hint</button></div><div id="hints"></div>');document.getElementById('submit').onclick=()=>{const v=document.getElementById('ans').value.trim().toLowerCase().replaceAll(' ','');const a=p.answer.toLowerCase().replaceAll(' ','');if(v===a){if(!solved(id))state.solved.push(id);if(p.items)state.items=[...new Set([...state.items,...p.items])];state.notes=[...new Set([...state.notes,p.note])];closeModal();if(p.video)showVideo(p.video,()=>{if(id==='final-door')showVideo('ending',render);else render()});else render()}else{state.attempts++;document.getElementById('hints').innerHTML='<p>Not yet. Try connecting the clue sources; no permanent penalty.</p>'}};document.getElementById('hint').onclick=()=>{state.hints[id]=(state.hints[id]||0)+1;const hs=p.hint||['Review your notebook.','Connect the newest clue to this lock.','Check README for the full demo answer list.'];document.getElementById('hints').innerHTML=hs.slice(0,Math.min(3,state.hints[id])).map(x=>'<p>💡 '+x+'</p>').join('')}}
function modal(html){app.insertAdjacentHTML('beforeend','<div class="modal" id="modal"><div class="panel card">'+html+'<p><button id="close">Close</button></p></div></div>');document.getElementById('close').onclick=closeModal}function closeModal(){document.getElementById('modal')?.remove()}
function showVideo(id,done){const v=videos[id];modal('<h2 class="brass">Cinematic: '+id+'</h2><video style="width:100%;background:#000" src="'+v[0]+'" poster="'+v[1]+'" controls autoplay muted></video><p>Captions: '+v[2]+'</p><p>If the placeholder video cannot play, use Continue; game logic still advances.</p><button id="continue">Continue</button>');document.getElementById('continue').onclick=()=>{closeModal();done&&done()}}
render();
`);
console.log('dist generated: open dist/index.html or run python3 -m http.server 4173 -d dist');
